name: dart_converters
description: CLI to do various file conversions
version: 0.0.2
homepage: https://github.com/SPiercer/dart_converters

environment:
  sdk: '>=2.16.2 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  args: ^2.3.0
executables:
  dart_converters: dart_converters